version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet build -c Release ./dotnet-core-xunit-example-master/dotnet-core-xunit/dotnet-core-xunit.csproj
            - dotnet test -c Release ./dotnet-core-xunit-example-master/dotnet-core-xunit-test/dotnet-core-xunit-test.csproj --collect:'XPlat Code Coverage' --logger:'trx;logFilename=report.xml;verbosity=detailed' --results-directory ./testresults 
            #- dotnet test -c Release ./dotnet-core-xunit-example-master/dotnet-core-xunit-test/dotnet-core-xunit-test.csproj --logger trx --results-directory ./testresults
reports:
    DotnetTestExamples:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'
